### ISSUE TITLE
No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (

### ISSUE THREAD

**Issue by karthickbrlab** [c-zhou/yahs#66]
my out.JBAT.log file generated is empty.

(java -jar -Xmx32G juicer_tools.1.9.9_jcuda.0.8.jar pre out_JBAT.txt out_JBAT.hic.part <(cat out_JBAT.log  | grep PRE_C_SIZE | awk '{print $2" "$3}')) && (mv out_JBAT.hic.part out_JBAT.hic)
cat: out_JBAT.log: No such file or directory
Not including fragment map
Start preprocess
Writing header
Writing body
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.mergeAndWriteBlocks(Preprocessor.java:1650)
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.access$000(Preprocessor.java:1419)
	at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:832)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:582)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:346)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:116)
	at juicebox.tools.HiCTools.main(HiCTools.java:96)

**Comment by ColinR01** [comment]
HI, 
   @karthickbrlab I have also encountered the same problem，have you solved your forehead problem? @c-zhou If possible, could you give me some advice？I would be very grateful.
---------------------------------------------------------------------------------------------------------------------------------------------

_**Command and error：**_

java -jar -Xmx32G juicer_tools.2.10.01.jar pre  alignments_sorted.txt out.hic asm_size
WARN [2023-10-08T09:46:32,647]  [Globals.java:138] [main]  Development mode is enabled
Skipping 31625512
Using 1 CPU thread(s)
Not including fragment map
Start preprocess
Writing header
Writing body
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
	at juicebox.tools.utils.original.MatrixZoomDataPP.mergeAndWriteBlocks(MatrixZoomDataPP.java:432)
	at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:1032)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:675)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:434)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:161)
	at juicebox.tools.HiCTools.main(HiCTools.java:94)

_**The head of alignments_sorted.txt is :**_

0       scaffold_1      1000000 0       1       scaffold_1      1002441 1
0       scaffold_1      1000000 0       1       scaffold_1      3536478 1
0       scaffold_1      1000000 0       1       scaffold_1      988566  1
0       scaffold_1      1000000 0       1       scaffold_1      999885  1
0       scaffold_1      100000  0       1       scaffold_1      74393   1
0       scaffold_1      100000  0       1       scaffold_1      99823   1
0       scaffold_1      100000  0       1       scaffold_1      99918   1
0       scaffold_1      1000001 0       1       scaffold_1      4122743 1
0       scaffold_1      1000001 0       1       scaffold_1      999892  1
0       scaffold_1      10000   0       1       scaffold_1      10072   1
0       scaffold_1      10000   0       1       scaffold_1      10159   1
0       scaffold_1      10000   0       1       scaffold_1      9825    1

**Comment by karthickbrlab** [comment]
Hi colin. 
It worked for me. 
I just rerun 
(juicer pre hic-to-contigs.bin scaffolds_final.agp contigs.fa.fai | sort -k2,2d -k6,6d -T ./ --parallel=8 -S32G | awk 'NF' > alignments_sorted.txt.part) && (mv alignments_sorted.txt.part alignments_sorted.txt). 

and make sure the scaffold details remains in the terminal. And runt the next one

**Comment by zhangyuxin1012** [comment]
> juicer pre hic-to-contigs.bin scaffolds_final.agp contigs.fa.fai | sort -k2,2d -k6,6d -T ./ --parallel=8 -S32G | awk 'NF' > alignments_sorted.txt.part) && (mv alignments_sorted.txt.part alignments_sorted.txt
I have also encountered the same problem，have you solved your forehead problem? @c-zhou If possible, could you give me some advice？I would be very grateful.


java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.mergeAndWriteBlocks(Preprocessor.java:1650)
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.access$000(Preprocessor.java:1419)
	at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:832)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:582)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:346)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:116)
	at juicebox.tools.HiCTools.main(HiCTools.java:96)

**Comment by c-zhou** [comment]
Hi @zhangyuxin1012,

Are there any records in the `alignments_sorted.txt`? If yes, what is 'juicer_tools' version you are using? We indeed had problems with version 2 juicer_tools sometimes.

Best,
Chenxi

**Comment by zhangyuxin1012** [comment]
When I ran the last step, the log file told me that there was a problem with the data in the out.hic

[I::main_pre] Version: 1.2

[I::main_pre] CMD: juicer pre yahs.out.bin yahs.out_scaffolds_final.agp /public/home/zhangyuxin/Agropyron_cristatum/WHXWZB-2023080085A/raw_data/PB/CCS/MB-89/bam/hifi_fq/01_Assembly/genome/draft.asm.fasta.fai

[I::main_pre] Real time: 6184.288 sec; CPU: 128.810 sec; Peak RSS: 0.002 GB

java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.

at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.mergeAndWriteBlocks(Preprocessor.java:1650)

at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.access$000(Preprocessor.java:1419)

at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:832)

at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:582)

at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:346)

at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:116)

at juicebox.tools.HiCTools.main(HiCTools.java:96)




alignments_sorted.txt This file is very large, it has 14 G, because my genome is relatively large, it is expected to be 6.5G, the file view the screenshot below










I don't know. What's wrong? Could you give me some guidance to help me solve this problem?

-----原始邮件-----
发件人:c-zhou ***@***.***>
发送时间:2024-07-18 18:50:06 (星期四)
收件人: c-zhou/yahs ***@***.***>
抄送: abcdefg ***@***.***>, Mention ***@***.***>
主题: Re: [c-zhou/yahs] No reads in Hi-C contact matrices. (Issue #66)






Hi @zhangyuxin1012,

Are there any records in the alignments_sorted.txt? If yes, what is 'juicer_tools' version you are using? We indeed had problems with version 2 juicer_tools sometimes.

Best,
Chenxi

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>










复旦大学江湾新校区生命科学学院G411
上海市杨浦区淞沪路2005号, 200438
School of Life Sciences, Fudan University
Room G411, 2005#Songhu Road, Shanghai 200438, China
Mobile: 186-4207-0433

**Comment by zhangyuxin1012** [comment]
This command line I use seems to be the version you recommend           java -jar -Xmx64G /public/home/yudunyang/Tools/juicer-1.6/CPU/common/juicer_tools.1.9.9_jcuda.0.8.jar pre alignments_sorted.txt out.hic.part scaffolds_final.chrom.sizes    


2024-07-18 19:52:54 "c-zhou" ***@***.***> 写道：

java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.

This error was generated by juicer_tools (https://github.com/aidenlab/juicer/wiki/Download) - not yahs's juicer pre. Which version are you using? We had problems with versions 2.x. If that is what you are using, you can switch to a version 1.x, e.g., this one https://s3.amazonaws.com/hicfiles.tc4ga.com/public/juicer/juicer_tools.1.9.9_jcuda.0.8.jar.

Chenxi

**Comment by c-zhou** [comment]
The `alignments_sorted.txt` and `scaffolds_final.chrom.sizes` are two files required by `juicer_tools` for generating a HiC map. If you did not see anything wrong with them, you might contact the `juicer_tools` team for help. You can also try some other versions.

Chenxi

**Comment by zhangyuxin1012** [comment]
The file for scaffold sizes should contain two columns - scaffold name and scaffold size, which can be taken from the first two columns of the FASTA index file.   # awk '{print $1, $2}' $contigsFasta.fai > scaffolds_final.chrom.sizes  Is it this file? I don't seem to understand the meaning of this document.

**Comment by c-zhou** [comment]
That is right. You can probably have a look at the JuiceBox documents https://github.com/aidenlab/juicer/wiki/. The BIN file is used solely to speed up the process. Alternatively, you can map your HiC data to the assembly and follow the JuiceBox procedure.

**Comment by avera1988** [comment]
Hi,

I found exactly the same problem when running the juicer_tools pre command:

```bash
 java -jar juicer_tools.1.9.9_jcuda.0.8.jar pre yahs.out.bin yahs.out_scaffolds_final.agp Danny_Flye2.8_10k.mod.fasta.fai
Skipping Danny_Flye2.8_10k_scaffold_9992        1588233 2685465717      1588233 1588234
Not including fragment map
Start preprocess
Writing header
Writing body
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
        at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.mergeAndWriteBlocks(Preprocessor.java:1650)
        at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.access$000(Preprocessor.java:1419)
        at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:832)                                                                                                            at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:582)
        at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:346)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:116)
        at juicebox.tools.HiCTools.main(HiCTools.java:96)
```

I noticed the .bin and .agp files are super small:

```
530K Oct 31 14:29 yahs.out_r05_break.agp
 8 Oct 31 14:28 yahs.out.bin

```

I am wondering if this is okay?

Thank you in advance for your help.

Best!

Arturo.
