### ISSUE TITLE
juicer_tools pre runs for days then encounters java.lang.NullPointerException

### ISSUE THREAD

**Issue by ethan-baldwin** [c-zhou/yahs#81]
I have scaffolded an assembly using yahs and am trying to manually curate it in JBAT, but I am running into issues using juicer_tools pre. I know that this tool is not part of yahs but since I'm running it using the output of yahs I figured I would try here first. 

This is a phased assembly and is happening with both haplotypes. One hap is ~3.8gb and 2200 contigs, and is scaffolded into 1700 scaffolds w/ yahs. The other is 3.4 gb, 1500 contigs, scaffolded into 900 scaffolds. 

Using the command in the readme:

```
(java -jar -Xmx32G juicer_tools.1.9.9_jcuda.0.8.jar pre out_JBAT.txt out_JBAT.hic.part <(cat out_JBAT.log  | grep PRE_C_SIZE | awk '{print $2" "$3}')) && (mv out_JBAT.hic.part out_JBAT.hic)
``` 

The job will run for 3 days and result in a .hic file a few mb in size, or sometimes run out of memory. If I give it more memory and threads, it will get a bit further and then give this error:

```
java.lang.NullPointerException
	at juicebox.data.iterator.ListOfListIterator.hasNext(ListOfListIterator.java:44)
	at juicebox.data.iterator.IteratorContainer.getNumberOfContactRecords(IteratorContainer.java:54)
	at juicebox.data.iterator.ListOfListIteratorContainer.getIsThereEnoughMemoryForNormCalculation(ListOfListIteratorContainer.java:56)
	at juicebox.tools.utils.norm.NormalizationCalculations.<init>(NormalizationCalculations.java:59)
	at juicebox.tools.utils.norm.GenomeWideNormalizationVectorUpdater.getWGVectors(GenomeWideNormalizationVectorUpdater.java:167)
	at juicebox.tools.utils.norm.GenomeWideNormalizationVectorUpdater.updateHicFileForGWfromPreAddNormOnly(GenomeWideNormalizationVectorUpdater.java:132)
	at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:159)
	at juicebox.tools.clt.old.AddNorm.launch(AddNorm.java:83)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:185)
	at juicebox.tools.HiCTools.main(HiCTools.java:97)

``` 

Any help would be great.

**Comment by c-zhou** [comment]
Hello @ethan-baldwin,

We sometimes see this problem as well. From our experience, juicer_tools seems to have problems when dealing with too many sequences. I would suggest excluding short sequences from HiC map construction, e.g., removing all scaffolds shorter than 10Kb. You can increase this size threshold if it does not reduce your scaffold number very much. You can do this by replacing `cat out_JBAT.log  | grep PRE_C_SIZE | awk '{print $2" "$3}'` with `cat out_JBAT.log  | grep PRE_C_SIZE | awk -v L=10000 '{if($3>=L) print $2" "$3}'` in you command. 

Best,
Chenxi

**Comment by ethan-baldwin** [comment]
Hi Chenxi,

The output of those commands are the same since the only line in the out_JBAT.log file starting with Pre_C_SIZE is the total assembly size. Here is an example of my out.JBAT.log:

`[I::main_pre] make juicer pre input from BIN file yahs.out.bin
[I::make_juicer_pre_file_from_bin] 139480245 read pairs processed
[I::main_pre] genome size: 3816252541
[I::main_pre] scale factor: 2
[I::main_pre] chromosome sizes for juicer_tools pre -
PRE_C_SIZE: assembly 1908126270
[I::main_pre] JUICER_PRE CMD: java -Xmx36G -jar ${juicer_tools} pre yahs_hap1_no_ec.txt yahs_hap1_no_ec.hic <(echo "assembly 1908126270")
[I::main_pre] Version: 1.1
[I::main_pre] CMD: juicer pre -a -o yahs_hap1_no_ec yahs.out.bin yahs.out_scaffolds_final.agp sarracenia.asm.dip.hap1.p_ctg.fa.fai
[I::main_pre] Real time: 86.065 sec; CPU: 54.864 sec; Peak RSS: 0.003 GB
`

I have tried excluding contigs greater that 100kb in the yahs command e.g `yahs -l 100000` and it does not significantly reduce the number of resulting scaffolds. In fact, there are more scaffolds in the output than there were contigs >100kb in the assembly. I may try running yahs with this filter and no error correction to see if I can reduce the number of scaffolds that way.

If you know of another way to reduce the number of scaffolds going into juicer_tools pre let me know.

Thanks,
Ethan

**Comment by c-zhou** [comment]
Hi @ethan-baldwin,

I see. This is the assembly mode. Can you show me the command before this? I guess you ran something like `juicer pre -a -o yahs_hap1_no_ec ...`. Is that correct?

Best,
Chenxi

**Comment by c-zhou** [comment]
Oh sorry, I see the command in log file.

**Comment by c-zhou** [comment]
Then you run `(java -jar -Xmx32G juicer_tools.1.9.9_jcuda.0.8.jar pre yahs_hap1_no_ec.txt yahs_hap1_no_ec.hic.part <(cat out_JBAT.log | grep PRE_C_SIZE | awk '{print $2" "$3}')) && (mv yahs_hap1_no_ec.hic.part yahs_hap1_no_ec.hic)` and got this error. Is that correct?

Chenxi

**Comment by c-zhou** [comment]
Also, which version of juicer_tools did you use? We indeed saw problems with newer versions.

Chenxi

**Comment by c-zhou** [comment]
It is very likely a problem caused by the juicer_tools version, especially if you are using version 2. You could try this version `juicer_tools.1.9.9_jcuda.0.8.jar`. You can directly download the jar file from here https://github.com/aidenlab/juicer/wiki/Download#version-199.

**Comment by c-zhou** [comment]
I have an access denial problem downloading jar files from that page. Not sure what happened. Chenxi

**Comment by ethan-baldwin** [comment]
I am getting  ERROR 403: Forbidden.

**Comment by c-zhou** [comment]
It might be good to ask the juicer_tools team to help.

I do think this is the juicer_tools version problem. I remember now this problem had been seen before. See [issue 4](https://github.com/c-zhou/yahs/issues/4) and [this comment](https://github.com/c-zhou/yahs/issues/4#issuecomment-997503060).

Chenxi

**Comment by ethan-baldwin** [comment]
I managed to find someone with a v 1.9.9 jar file, and it appears to be working correctly now. Thanks for your help!

**Comment by c-zhou** [comment]
That is great. You may also need Juicebox version 1 instead of 2 for manual editing. Chenxi
